---
- name: Create a text file
  hosts: all
  gather_facts: True
  tasks:
    - name: Display all variables/facts known for a host
      debug: var=hostvars['UC1WFTCTEST04']
      
    - name: Create a text file taco
      file: path=/etc/taco_test.txt state=touch
      tags:
        - taco
    - name: Create a test file salad
      file: path=/etc/salad_test.txt state=touch
      tags:
        - salad
