---
- name: Create a server
  hosts: localhost
  vars:
    server_group: 'Default Group'
    server_count: 1
  gather_facts: False
  connection: local
  tasks:
    - name: Create a server at CLC
      clc_server:
        name: ubusvr
        template: ubuntu-14-64
        count: "{{ server_count }}"
        group: "{{ server_group }}"
        password: test
      register: clc

    - name: debug
      debug: var=clc.server_ids
      
    - name: Add New Server to the host list
      add_host:
        name={{ item.name }}
        ansible_ssh_host={{ item.ipaddress }}
        ansible_ssh_user=root
        ansible_ssh_pass=test
      with_items: clc.servers
      
- name: ping all hosts
  hosts: all
  tasks:
    - name: Check that the hosts alive
      action: ping
      
- name: Create a test file
  hosts: all
  tasks:
    - name: Create a text file test
      file: path=test.txt state=touch
