---
- name: Create a text file
  hosts: all
  vars:
    http_port: 80
    variable1: value1
    variable2: value2
    
  tasks:
    - name: Create a text file taco
      file: path=taco_test.txt state=touch
      tags:
        - taco
      
    - name: display job_id
      debug: var="{{ rnr_job_id }}"
      
    - name: display execution_id
      debug: var="{{ rnr_execution_id }}"
      
    - name: Create a test file salad
      file: path=salad_test.txt state=touch
      tags:
        - salad
