---
- name: Create a text file
  hosts: all
  vars:
    http_port: 80
    variable1: value1
    variable2: value2
    
  tasks:
    - name: Create a text file taco
      file: path=taco_test.txt state=touch
      tags:
        - taco
        
    - name: display property1	
      debug: var={{ property1 }}
      
    - name: display property2
      debug: var={{ property2 }}      
      
    - name: Create a test file salad
      file: path=salad_test.txt state=touch
      tags:
        - salad
