---
- name: Create a text file
  hosts: all
  gather_facts: true
  tasks:
    - name: Create a text file taco
      file: path=taco_test.txt state=touch
      tags:
        - taco
    - name: Create a test file salad
      file: path=salad_test.txt state=touch
      tags:
        - salad
