---
- name: Create a text file
  hosts: all
  gather_facts: False
  tasks:
    - name: Create a text file taco
      file: path=/tmp/taco_test.txt state=touch
      tags:
        - taco
    - name: Create a test file salad
      file: path=/tmp/salad_test.txt state=touch
      tags:
        - salad
