---
- name: Create a text file
  hosts: all
  gather_facts: False
  tasks:
    - name: Create a text file taco
      file: src=/tmp/taco_test.txt
      tags:
        - taco
    - name: Create a test file salad
      file: src=/tmp/salad_test.txt
      tags:
        - salad
