---
- name: Create a text file
  hosts: all
  gather_facts: False
  tasks:
    - name: Create a text file tacoo
      file: path=/etc/taco_test.txt state=touch
      tags:
        - taco
    - name: Create a test file saladd
      file: path=/etc/salad_test.txt state=touch
      tags:
        - salad
