---
- name: modify clc server
  hosts: all
  gather_facts: False
  connection: local
  tasks:
    - name: Modify Server at CLC
      clc_modify_server:
        server_ids:
            - UC1WFADOSTST01
        cpu: 2
        memory: 16
        wait: True
        state: present
      register: clc
